apiVersion: v1
kind: Service
metadata:
  name: django-todo
spec:
  selector:
    app: django-todo
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000        # service port inside cluster
      targetPort: 8000  # pod port
      nodePort: 30080   # port on localhost

